### PR TITLE
Update MonthView.java

### PR DESCRIPTION
**Pull request by devDroidRaul**
need to show year. it gets difficult to identify which year is this month referring to when  we do horizontal scroll on the recyclerview. we can have the month view this view
.
MAY
2017

### CODE REVIEW

**Comment by badoualy** [comment]
Totally agree!
I'll look into it and make it so that we can enable it or not :)

**Comment by badoualy** [comment]
Sorry for the delay.
I think keeping the last 2 digit of the year is enough and it will save some space and avoid having too much information. What do you think?

**Comment by devDroidRaul** [comment]
hey, two digit is also fine. just that , there has to be a way to identify corresponding year.

**Comment by badoualy** [comment]
I was thinking either
Mar 17 
or
Mar
17

**Comment by badoualy** [comment]
So, in the xml you can use:
```xml
        <attr name="mti_yearDigitCount" format="integer"/>
        <attr name="mti_yearOnNewLine" format="boolean"/>
```

or via code the same methods to configure it as you want, every should be happy :)

**Pull request merged**
